const wordlisttitle = "Franska - Chez Nous Kap 3a";

const words = [
  { front: "ta fast tjuven!", back: "au voleur !" },
  { front: "rea", back: "soldes" },
  { front: "jeans", back: "un jean" },
  { front: "en t-shirt", back: "un tee-shirt" },
  { front: "en kjol", back: "une jupe" },
  { front: "en blus", back: "un chemisier" },
  { front: "en jacka", back: "un blouson" },
  { front: "en klänning", back: "une robe" },

  { front: "hennes tjejkompis", back: "sa copine" },
  { front: "framför", back: "devant" },
  { front: "en klädaffär", back: "un magasin<br><br>de vêtements" },
  { front: "kläder", back: "vêtements" },
  { front: "fredag eftermiddag", back: "vendredi<br><br>après-midi" },
  { front: "i morgon", back: "demain" },
  { front: "det är fest", back: "il y a une fête" },
  { front: "hos", back: "chez" },
  { front: "kommer du?", back: "tu viens ?" },
  { front: "men", back: "mais" },
  { front: "jag har inget att ta på mig", back: "je n’ai rien à<br><br>me mettre" },
  { front: "ska vi gå in?", back: "on entre ?" },

  { front: "ok", back: "d’accord" },
  { front: "titta på", back: "regarde" },
  { front: "de blå jeansen", back: "le jean bleu" },
  { front: "kostar", back: "coûte" },
  { front: "jättecoolt", back: "hyper cool" },
  { front: "jag gillar blått", back: "j’aime le bleu" },
  { front: "jag gillar inte", back: "je n’aime pas" },
  { front: "samma", back: "le même" },
  { front: "i svart", back: "en noir" },
  { front: "försäljaren", back: "le vendeur" },
  { front: "varsågod", back: "tenez" },
  { front: "det sista (paret)", back: "le dernier" },
  { front: "provhytten", back: "la cabine d’essayage" },
  { front: "där borta", back: "là-bas" },
  { front: "jag kommer", back: "j’arrive" },
  { front: "jag ska prova", back: "je vais essayer" },
  { front: "den blå kjolen", back: "la jupe bleue" },
  { front: "bara, enbart", back: "seulement" },

  { front: "en flicka", back: "une fille" },
  { front: "annan", back: "autre" },
  { front: "tar", back: "prend" },
  { front: "byxorna", back: "le pantalon" },
  { front: "toppen!", back: "chouette !" },
  { front: "precis min storlek", back: "juste ma taille" },

  { front: "alla", back: "tout le monde" },
  { front: "letar efter", back: "cherche" },
  { front: "under", back: "sous" },
  { front: "borden", back: "les tables" },
  { front: "på", back: "sur" },
  { front: "stolarna", back: "les chaises" },
  { front: "i", back: "dans" },
  { front: "(utdrags)lådorna", back: "les tiroirs" },
  { front: "kassan", back: "la caisse" },
  { front: "bakom", back: "derrière" },
  { front: "de hittar inte", back: "ils ne trouvent pas" },

  { front: "ledsen", back: "désolé" },
  { front: "såld", back: "vendu" },
  { front: "erbjuder", back: "offre" },
  { front: "en liten present", back: "un petit cadeau" },
  { front: "en svart scarf", back: "une écharpe noire" },
  { front: "en storlek mindre", back: "une taille plus petite" },
  { front: "den går på rea för ...", back: "il est soldé à ..." }
];
