const wordlisttitle = "Fysik: Elektricitet";

const words = [
  { front: "Elektrisk laddning", back: "Allt material består av partiklar med laddning.<br><br>Det finns <b>positiv</b> och <b>negativ</b> laddning." },
  { front: "Atomkärna", back: "Atomens mitt. Den är <b>positivt laddad</b> eftersom den innehåller protoner." },
  { front: "Elektron", back: "En partikel med <b>negativ laddning</b> som finns runt atomkärnan." },
  { front: "Proton", back: "En partikel med <b>positiv laddning</b> som finns i atomkärnan." },
  { front: "Elektriskt neutral", back: "När ett ämne eller en atom har lika många <i>positiva</i> som <i>negativa</i> laddningar." },
  { front: "Repellerar", back: "När föremål med <b>samma laddning</b> stöter bort varandra." },
  { front: "Attraherar", back: "När föremål med <b>olika laddning</b> dras till varandra." },
  { front: "Spänning", back: "Skillnaden i laddning mellan två punkter, till exempel mellan batteriets pluspol och minuspol.<br><br>Spänning mäts i <b>volt (V)</b>." },
  { front: "Ström", back: "När elektroner rör sig i en ledning eller i en krets.<br><br>Ström mäts i <b>ampere (A)</b>." },
  { front: "Elektrisk krets", back: "En väg där strömmen kan gå från batteriet, genom till exempel en lampa, och tillbaka igen." },
  { front: "Sluten krets", back: "En krets som är hel, så att strömmen kan gå runt.<br><br>Utan sluten krets blir det <b>ingen ström</b>." },
  { front: "Volt (V)", back: "Enheten för <b>spänning</b>." },
  { front: "Ampere (A)", back: "Enheten för <b>ström</b>.<br><br>1 A = 1000 mA." },
  { front: "Ledare", back: "Ett ämne som leder ström bra, till exempel <b>metaller</b> som koppar och silver." },
  { front: "Isolator", back: "Ett ämne som <b>inte</b> leder ström bra, till exempel plast och glas." },
  { front: "Resistans", back: "Motstånd mot ström i ett ämne eller i en krets.<br><br>Resistans mäts i <b>ohm (Ω)</b>." },
  { front: "Resistor", back: "En komponent som har resistans och används för att <b>minska strömmen</b> i en krets." },
  { front: "Seriekoppling", back: "När flera komponenter sitter <b>efter varandra</b> i samma väg.<br><br>Om en lampa går sönder kan alla slockna." },
  { front: "Parallellkoppling", back: "När flera komponenter sitter i <b>olika grenar</b> i kretsen.<br><br>Om en lampa går sönder kan de andra ändå lysa." },
  { front: "Kortslutning", back: "När strömmen tar en <b>för lätt väg</b>, ofta för att ledningar kommer i kontakt med varandra.<br><br>Det kan bli farligt." },
  { front: "Säkring", back: "Skydd som bryter strömmen om den blir för stark, till exempel vid <b>överbelastning</b> eller <b>kortslutning</b>." },
  { front: "Skyddsjordning", back: "En extra säkerhet i vissa apparater som hjälper till att leda bort farlig ström." },
  { front: "Elektrisk energi", back: "Energi som kan omvandlas till andra energiformer, till exempel <b>ljus</b>, <b>värme</b> eller <b>rörelse</b>." },
  { front: "Varför är en atom oftast elektriskt neutral?", back: "För att den oftast har lika många <b>protoner</b> som <b>elektroner</b>." },
  { front: "Varför kan en lampa inte lysa i en öppen krets?", back: "För att kretsen inte är <b>sluten</b>.<br><br>Då kan inte strömmen gå runt." },
  { front: "Vad händer om spänningen tar slut i ett batteri?", back: "Då jämnas skillnaden mellan polerna ut och det blir <b>ingen ström</b>." },
  { front: "Varför leder metaller ström bra?", back: "För att de har elektroner som kan röra sig lätt genom materialet." },
  { front: "Varför används plast runt elledningar?", back: "För att plast är en <b>isolator</b> och skyddar mot elstötar." },
  { front: "Vad är skillnaden mellan serie- och parallellkoppling?", back: "<b>Seriekoppling</b>: komponenter sitter efter varandra i samma väg.<br><br><b>Parallellkoppling</b>: komponenter sitter i olika grenar." },
  { front: "Varför kan en kortslutning vara farlig?", back: "För att strömmen kan bli för stark och skapa <b>värme</b> eller brandrisk." },
  { front: "Vad gör en säkring i ett hus eller i en apparat?", back: "Den bryter strömmen om det blir fel, så att människor och saker skyddas." },
  { front: "Varför är el i badrum extra farligt?", back: "För att vatten och blöt hud minskar kroppens resistans, så att mer ström kan gå genom kroppen." },
  { front: "Varför säger man att elektrisk energi är lätt att omvandla?", back: "För att den enkelt kan bli till exempel <b>ljus</b>, <b>värme</b> eller <b>rörelse</b>." },
  { front: "Vad händer med strömmen om resistansen ökar i en krets?", back: "Strömmen <b>minskar</b>." }
];