const wordlisttitle = "Folkhälsa: Hälsofrämjande arbete och folkhälsoperspektiv";

const words = [
  { front: "Salutogent perspektiv", back: "Fokus på <b>vad som skapar hälsa</b> (inte vad som orsakar sjukdom).<br><br>Kopplat till <i>Antonovsky</i>." },
  { front: "KASAM (Sense of Coherence)", back: "<b>Begriplighet, hanterbarhet och meningsfullhet</b> stärker motståndskraft mot stress." },
  { front: "Primär prevention", back: "Förebygga att sjukdom uppstår.<br><br><i>Exempel:</i> vaccination." },
  { front: "Sekundär prevention", back: "Tidigt upptäcka sjukdom för att minska följder.<br><br><i>Exempel:</i> screening." },
  { front: "Tertiär prevention", back: "Minska komplikationer efter sjukdom.<br><br><i>Exempel:</i> rehabilitering." },
  { front: "Proportionate universalism", back: "Universella insatser som <b>anpassas efter behov</b> – för att minska ojämlikhet." },
  { front: "Socialt kapital", back: "Tillit, nätverk och socialt stöd som stärker hälsa i samhällen." },
  { front: "Health Impact Assessment (HIA)", back: "Systematisk analys av hur policyförslag påverkar hälsa." },
  { front: "Empowerment vs enablement", back: "<b>Empowerment:</b> ge makt.<br><b>Enablement:</b> skapa förutsättningar." },
  { front: "Advocacy vs lobbying", back: "<b>Advocacy:</b> påverkan för allmännytta.<br><b>Lobbying:</b> påverkan för särintresse." },
  { front: "Top-down vs bottom-up", back: "<b>Top-down:</b> uppifrån styrt (myndigheter).<br><b>Bottom-up:</b> från gräsrötter och lokala initiativ." },
  { front: "Settings-based vs population-based", back: "<b>Settings-based:</b> fokus på miljö/arena.<br><b>Population-based:</b> hela befolkningen." },
  { front: "Health inequalities vs health inequities", back: "<b>Inequalities:</b> skillnader.<br><b>Inequities:</b> orättvisa skillnader." },
  { front: "Intersectoral collaboration", back: "Samarbete mellan flera sektorer (t.ex. skola, transport, miljö) för hälsa." },
  { front: "Upstream vs downstream", back: "<b>Upstream:</b> samhällsorsaker till ohälsa.<br><b>Downstream:</b> individnivå, behandling." },
  { front: "Behavioural vs structural approach", back: "<b>Beteendeinriktat:</b> fokus på individens val.<br><b>Strukturellt:</b> fokus på policy och miljö." },
  { front: "Ecological fallacy", back: "Felaktigt att dra slutsatser om individer utifrån gruppdata." },
  { front: "Etiskt dilemma i hälsofrämjande arbete", back: "Balans mellan <b>autonomi</b> och <b>kollektivt ansvar</b>; hur mycket får man styra?" },
  { front: "Health policy cycle", back: "Cykel av <i>formulering → beslut → implementering → utvärdering</i>." },
  { front: "Evaluation (process, impact, outcome)", back: "<b>Process:</b> hur genomförs?<br><b>Impact:</b> direkt effekt.<br><b>Outcome:</b> långsiktig hälsa." },
  { front: "Participatory research", back: "Forskning <b>med</b> deltagande av målgruppen – inte bara <b>om</b> dem." },
  { front: "Social learning theory", back: "Människor lär sig genom att <b>observera andra</b>; modellinlärning." },
  { front: "Cultural competence", back: "Förmåga att förstå och agera respektfullt mot olika kulturella perspektiv." },
  { front: "Intersectionality", back: "Hälsoskillnader påverkas av flera faktorer samtidigt (t.ex. kön, klass, etnicitet)." },
  { front: "Resilience", back: "Förmåga att <b>hantera motgångar</b>; stärks genom stöd och delaktighet." },
  { front: "Stigma", back: "Negativa sociala etiketter som påverkar hälsa och självkänsla." },
  { front: "Lay knowledge", back: "Vardagskunskap om hälsa – ofta förbised men värdefull i planering." },
  { front: "Empirical vs normative theory", back: "<b>Empirical:</b> beskriver hur det är.<br><b>Normative:</b> hur det bör vara." },
  { front: "Critical public health", back: "Betonar <b>makt, ideologi och social rättvisa</b> i folkhälsa." },
  { front: "Sustainability in health promotion", back: "Långsiktiga insatser som kan fortsätta utan ständigt nytt stöd." },
  { front: "Capacity building", back: "Utveckla individers och organisationers förmåga att arbeta hälsofrämjande." }
];
