const wordlisttitle = "Folkhälsa: Wills, Nutbeam och Cross";

const words = [
  { front: "Hälsa (Health)", back: "Fysiskt, psykiskt och socialt välbefinnande – inte bara frånvaro av sjukdom." },
  { front: "Well-being (Välmående)", back: "Subjektivt mått på livstillfredsställelse – handlar om upplevelsen av att må bra." },
  { front: "Livskvalitet", back: "Hur nöjd man är med livet i stort – påverkas av hälsa men är inte samma sak." },
  { front: "Medicinska modellen", back: "Ser hälsa som frånvaro av sjukdom; fokus på behandling, inte orsaker." },
  { front: "Biopsykosocial modell", back: "Hälsa påverkas av biologiska, psykologiska och sociala faktorer i samspel." },
  { front: "Whitehead & Dahlgren-modellen", back: "Cirklar som visar hur individuella, sociala, ekonomiska och miljömässiga faktorer påverkar hälsa." },
  { front: "Social gradient", back: "Sambandet mellan socioekonomisk status och hälsa – högre status = bättre hälsa." },
  { front: "Whitehall-studierna", back: "Brittiska studier som visade tydlig social gradient i hälsa bland tjänstemän." },
  { front: "Ekologisk modell", back: "Hälsa formas på flera nivåer: individ, relationer, samhälle, policy." },
  { front: "Health promotion", back: "Att skapa förutsättningar för människor att förbättra sin hälsa." },
  { front: "Health education", back: "Att ge kunskap och förståelse om hälsa." },
  { front: "Disease prevention", back: "Att förebygga sjukdom.<br><br>*Primär* = innan, *sekundär* = tidig upptäckt, *tertiär* = minska följder." },
  { front: "Upstream interventions", back: "Åtgärder på samhällsnivå för att minska grundorsaker till ohälsa." },
  { front: "Equity (rättvisa)", back: "Alla ska ha lika möjligheter till hälsa – ta hänsyn till olika behov." },
  { front: "Empowerment", back: "Att stärka människors kontroll över sitt liv och sina beslut." },
  { front: "Delaktighet (Participation)", back: "Målgruppen ska involveras i planering och genomförande." },
  { front: "Ottawa Charter (1986)", back: "Grunddokument för hälsofrämjande: processerna *enable*, *mediate*, *advocate*." },
  { front: "De 5 principerna för health promotion", back: "Empowerment, delaktighet, rättvisa, samverkan, hållbarhet." },
  { front: "Hälsa som politik", back: "Hälsa formas av politiska beslut, resurser och makt." },
  { front: "Advocacy", back: "Att påverka politiska beslut och opinion för att förbättra hälsan." },
  { front: "Healthy Public Policy", back: "Alla politikområden ska främja hälsa (*Health in All Policies*)." },
  { front: "Settings approach", back: "Arbeta hälsofrämjande där människor lever sina liv – skola, arbetsplats, bostad, fängelse m.m." },
  { front: "Community empowerment", back: "När lokalsamhällen får makt att påverka sina egna villkor." },
  { front: "Stödjande miljöer (Supportive environments)", back: "Miljöer som underlättar hälsosamma val." },
  { front: "Health literacy (HL)", back: "Förmåga att förstå, värdera och använda hälsoinformation." },
  { front: "Critical Health Literacy (CHL)", back: "HL på strukturell nivå – kunna påverka samhälleliga villkor." },
  { front: "Epidemiologi", back: "Läran om sjukdomars förekomst och orsaker i befolkningar." },
  { front: "Maslows behovstrappa", back: "Människans behov i ordning:<br><br>1. Fysiologiska<br>2. Trygghet<br>3. Tillhörighet<br>4. Uppskattning<br>5. Självförverkligande" },
  { front: "PRECEDE–PROCEED", back: "Planeringsmodell:<br><br>*PRECEDE* = analysera behov<br>*PROCEED* = genomföra och utvärdera." },
  { front: "Intervention Mapping", back: "Stegvis planering: behov, mål, teori, metod, implementering, utvärdering." },
  { front: "Health Belief Model (HBM)", back: "Hälsobeteende styrs av upplevd risk, fördelar, hinder och egen förmåga." },
  { front: "Transtheoretical Model (TTM)", back: "Beteendeförändring sker i steg:<br><br>*Precontemplation → Contemplation → Action → Maintenance*." },
  { front: "Theory of Planned Behaviour (TPB)", back: "Intention + upplevd kontroll → beteende." },
  { front: "Social Cognitive Theory (Bandura)", back: "Lärande genom observation – *self-efficacy* centralt för förändring." },
  { front: "Diffusion of Innovation", back: "Hur nya idéer sprids i ett samhälle – från innovatörer till majoritet." },
  { front: "Social Marketing", back: "Användning av marknadsföringsprinciper för att påverka hälsobeteende." },
  { front: "Behaviour Change Communication (BCC)", back: "Kommunikationsstrategier för att påverka specifika beteenden." },
  { front: "Media Advocacy", back: "Att använda media för att påverka samhällsförändring – inte bara individer." },
  { front: "Assets-based approach", back: "Bygga på resurser och styrkor i samhället, inte brister." },
  { front: "Deficit model", back: "Fokuserar på vad människor saknar – kritiseras för att skuldbelägga." },
  { front: "Two-way communication", back: "Dialogbaserad, deltagande kommunikation (motsats till top-down)." },
  { front: "Power with / Power over", back: "*Power with* = samarbetsbaserad makt.<br>*Power over* = hierarkisk kontroll." },
  { front: "Transformative education", back: "Lärande som förändrar individens världsbild och självförståelse." },
  { front: "Freire – conscientization", back: "Medvetandegörande och frigörelse genom reflektion och dialog." },
  { front: "Dewey – experiential learning", back: "Vi lär genom att göra och reflektera i sociala sammanhang." },
  { front: "Buber – dialogisk relation", back: "“Jag–Du”-relation – äkta möten bygger på ömsesidighet." },
  { front: "Neoliberalt paradigm", back: "Synsätt där individen bär ansvar för hälsa – kritiseras som ojämlikt." },
  { front: "Victim blaming", back: "Att skuldbelägga individer för sin ohälsa snarare än att se strukturer." },
  { front: "Nudging", back: "Små *knuffar* för att främja hälsosamma val – effektivt men kan hota autonomi." },
  { front: "Situated social practice", back: "Fokuserar på hälsorelaterade vanor i sitt sociala sammanhang, inte bara individens val." },
  { front: "Life course perspective", back: "Hälsan formas under hela livet – tidiga insatser ger långvarig effekt." },
  { front: "Equity vs Equality", back: "*Equality* = lika för alla.<br>*Equity* = rättvisa utifrån behov." },
  { front: "Social determinants of health", back: "De samhälleliga faktorer som påverkar hälsa – arbete, utbildning, boende, miljö." }
];
