const wordlisttitle = "Folkhälsa: Hälsopromotion"; 

const words = [
  { front: "Vad menas med att hälsa är en social konstruktion?", back: "→ Hälsa formas av <b>samhällsnormer, kultur och värderingar</b>, inte bara biologi." },
  { front: "Varför är empowerment centralt i hälsofrämjande arbete?", back: "→ För att människor själva ska kunna <b>påverka sina livsvillkor och hälsobeslut</b>." },
  { front: "Vad innebär begreppet “health in all policies”?", back: "→ Att <b>alla politikområden</b>, inte bara sjukvården, ska beakta hälsa." },
  { front: "Hur skiljer sig equity från equality?", back: "→ <b>Equality</b> = lika för alla.<br><b>Equity</b> = rättvisa utifrån behov." },
  { front: "Vad innebär ett livscykelperspektiv på hälsa?", back: "→ Att <b>hälsan formas genom hela livet</b> och att tidiga insatser ger störst effekt." },
  { front: "Varför kan health literacy ses som ett demokratiskt begrepp?", back: "→ För att <b>förståelse och inflytande</b> över hälsobeslut är en förutsättning för delaktighet." },
  { front: "Hur kan Maslows behovstrappa användas i hälsopromotion?", back: "→ Genom att förstå att <b>grundläggande behov</b> måste tillfredsställas innan livsstilsförändring kan ske." },
  { front: "Vad menas med upstream och downstream interventions?", back: "→ <b>Upstream</b> = samhällsnivå (strukturer).<br><b>Downstream</b> = individnivå (beteenden)." },
  { front: "Vad är “social marketing” inom folkhälsa?", back: "→ Att använda <b>marknadsföringstekniker</b> för att sprida hälsobudskap." },
  { front: "Varför kritiseras begreppet “victim blaming”?", back: "→ Det <b>skuldbelägger individer</b> för ohälsa och ignorerar strukturella orsaker." },
  { front: "Vad betyder “settings approach”?", back: "→ Att arbeta hälsofrämjande <b>där människor lever sina liv</b> – t.ex. i skolan eller på arbetsplatsen." },
  { front: "Varför är makt ett etiskt problem i hälsokommunikation?", back: "→ Den som kommunicerar kan <b>påverka och styra andra</b> – risk för ojämlik relation." },
  { front: "Vad innebär “enable, mediate, advocate” i Ottawa Charter?", back: "→ <b>Enable:</b> möjliggöra handling.<br><b>Mediate:</b> förmedla samverkan.<br><b>Advocate:</b> påverka beslut för hälsa." },
  { front: "Hur kan intersektoriellt samarbete bidra till jämlik hälsa?", back: "→ Genom att <b>flera samhällssektorer</b> gemensamt angriper grundorsaker till ohälsa." },
  { front: "Vad är syftet med epidemiologi i hälsofrämjande arbete?", back: "→ Att <b>identifiera mönster och orsaker</b> till sjukdomar i befolkningen." },
  { front: "Varför är delaktighet viktig i hälsofrämjande projekt?", back: "→ Ökar <b>motivation, relevans och hållbarhet</b> eftersom människor äger processen." },
  { front: "Vad innebär “behavioural change communication”?", back: "→ Kommunikationsstrategier som syftar till att <b>förändra specifika hälsobeteenden</b>." },
  { front: "Varför talar Cross et al. om kommunikation som konversation?", back: "→ För att betona <b>dialog, ömsesidighet och respekt</b> snarare än envägskommunikation." },
  { front: "Vad menas med “power with” istället för “power over”?", back: "→ Att <b>samarbeta med människor</b> snarare än att kontrollera dem." },
  { front: "Vad är “transformativt lärande”?", back: "→ Lärande som <b>förändrar hur människor förstår</b> sig själva och sin omvärld." },
  { front: "Hur kan media advocacy påverka folkhälsan?", back: "→ Genom att <b>forma opinion</b> och trycka på för policyförändringar." },
  { front: "Vad menas med “assets-based approach”?", back: "→ Att <b>utgå från människors resurser och styrkor</b> i stället för brister." },
  { front: "Vad innebär social gradient i hälsa?", back: "→ Att hälsa systematiskt <b>förbättras med stigande socioekonomisk position</b>." },
  { front: "Vilken kritik finns mot det neoliberala perspektivet på hälsa?", back: "→ Det <b>lägger ansvar på individen</b> och bortser från sociala och ekonomiska faktorer." },
  { front: "Varför används planeringsmodeller i hälsopromotion?", back: "→ För att skapa <b>struktur, tydlighet och möjlighet till utvärdering</b>." },
  { front: "Vad innebär participatory research?", back: "→ Att forskningen sker <b>tillsammans med deltagarna</b>, inte bara om dem." },
  { front: "Hur skiljer sig empirisk och normativ teori inom folkhälsa?", back: "→ <b>Empirisk:</b> beskriver verkligheten.<br><b>Normativ:</b> säger hur den bör vara." },
  { front: "Varför är socialt stöd viktigt för hälsa?", back: "→ Det <b>minskar stress</b>, stärker coping och främjar psykiskt välbefinnande." },
  { front: "Vad innebär resilience i folkhälsosammanhang?", back: "→ Förmågan att <b>stå emot och återhämta sig</b> från motgångar." },
  { front: "Varför kallas hälsopromotion ibland “den militanta grenen” av folkhälsan?", back: "→ För att den <b>utmanar maktstrukturer</b>, kräver <b>social rättvisa</b> och ifrågasätter status quo." }
];

