const wordlisttitle = "Öva på begrepp om Hälsopromotion och folkhälsa";

const words = [
  { front: "Hälsa som social konstruktion", back: "Hälsa formas av <b>samhällsnormer, kultur och värderingar</b> – inte bara av biologi." },
  { front: "Empowerment i hälsofrämjande arbete", back: "Att människor själva får <b>kontroll och inflytande</b> över sina livsvillkor och hälsobeslut." },
  { front: "Health in all policies", back: "Alla politikområden ska <b>beakta hälsa</b>, inte bara sjukvården." },
  { front: "Equity vs Equality", back: "<b>Equality</b> = lika för alla.<br><b>Equity</b> = rättvisa utifrån behov." },
  { front: "Livscykelperspektiv på hälsa", back: "Hälsan formas genom hela livet – <i>tidiga insatser ger störst effekt.</i>" },
  { front: "Health literacy som demokratiskt begrepp", back: "Förståelse och inflytande över hälsobeslut är <b>en förutsättning för delaktighet</b>." },
  { front: "Maslows behovstrappa i hälsopromotion", back: "Grundläggande behov måste tillfredsställas <br>innan livsstilsförändringar kan ske." },
  { front: "Upstream och Downstream interventions", back: "<b>Upstream:</b> samhällsnivå (strukturer).<br><b>Downstream:</b> individnivå (beteenden)." },
  { front: "Social marketing", back: "Användning av <b>marknadsföringstekniker</b> för att sprida hälsobudskap." },
  { front: "Victim blaming", back: "Att skuldbelägga individer för ohälsa <br>och ignorera strukturella orsaker." },
  { front: "Settings approach", back: "Arbeta hälsofrämjande där människor lever sina liv – t.ex. i <b>skolan</b> eller på <b>arbetsplatsen</b>." },
  { front: "Makt som etiskt problem i hälsokommunikation", back: "Den som kommunicerar kan <b>påverka och styra</b> andra – risk för ojämlik relation." },
  { front: "Enable, Mediate, Advocate (Ottawa Charter)", back: "<b>Enable:</b> möjliggöra handling.<br><b>Mediate:</b> förmedla samverkan.<br><b>Advocate:</b> påverka beslut för hälsa." },
  { front: "Intersektoriellt samarbete", back: "Flera sektorer arbetar tillsammans för att <b>minska ojämlikhet i hälsa</b>." },
  { front: "Epidemiologi i hälsofrämjande arbete", back: "Identifierar <b>mönster och orsaker</b> till sjukdomar i befolkningen." },
  { front: "Delaktighet i hälsofrämjande projekt", back: "Ökar <b>motivation, relevans och hållbarhet</b> eftersom människor äger processen." },
  { front: "Behavioural change communication", back: "Kommunikation som syftar till att <b>förändra specifika hälsobeteenden</b>." },
  { front: "Kommunikation som konversation (Cross et al.)", back: "Betonar <b>dialog, ömsesidighet och respekt</b> – inte envägskommunikation." },
  { front: "Power with vs Power over", back: "<b>Power with:</b> samarbete.<br><b>Power over:</b> kontroll och dominans." },
  { front: "Transformativt lärande", back: "Lärande som <b>förändrar hur människor förstår</b> sig själva och sin omvärld." },
  { front: "Media advocacy", back: "Används för att <b>forma opinion</b> och påverka <b>policyförändringar</b>." },
  { front: "Assets-based approach", back: "Utgår från människors <b>styrkor och resurser</b> istället för brister." },
  { front: "Social gradient i hälsa", back: "Hälsa förbättras systematiskt med <b>stigande socioekonomisk position</b>." },
  { front: "Neoliberal kritik inom hälsa", back: "Fokuserar för mycket på <b>individens ansvar</b> och bortser från strukturella faktorer." },
  { front: "Planeringsmodeller i hälsopromotion", back: "Ger <b>struktur, tydlighet</b> och möjlighet till <b>utvärdering</b>." },
  { front: "Participatory research", back: "Forskning som sker <b>tillsammans med deltagarna</b>, inte om dem." },
  { front: "Empirisk vs Normativ teori", back: "<b>Empirisk:</b> beskriver verkligheten.<br><b>Normativ:</b> säger hur den bör vara." },
  { front: "Socialt stöd och hälsa", back: "Minskar <b>stress</b>, stärker <b>coping</b> och främjar <b>psykiskt välbefinnande</b>." },
  { front: "Resilience i folkhälsan", back: "Förmågan att <b>stå emot och återhämta sig</b> från motgångar." },
  { front: "Hälsopromotion som 'militanta grenen'", back: "Utmanar <b>maktstrukturer</b>, kräver <b>social rättvisa</b> och ifrågasätter status quo." }
];
