const wordlisttitle = "Historia: Svåra allmänna ord";

const words = [
  { front: "kronologi", back: "Att lägga händelser i rätt ordning i tiden. Vad hände <b>först</b>, <b>sedan</b> och <b>sist</b>?" },
  { front: "epok", back: "En lång tidsperiod i historien. Till exempel stenåldern eller medeltiden." },
  { front: "orsak", back: "Något som gör att något annat händer. Exempel: Missväxt kan vara en orsak till svält." },
  { front: "konsekvens", back: "Det som händer efteråt som följd av något. Exempel: Ett krig kan få konsekvensen att många måste flytta." },
  { front: "kontinuitet", back: "Sådant som fortsätter att vara ungefär likadant under lång tid." },
  { front: "förändring", back: "När något blir annorlunda än det var förut." },
  { front: "likhet", back: "När två saker är lika varandra." },
  { front: "skillnad", back: "När två saker inte är lika varandra." },
  { front: "samband", back: "När olika saker hör ihop eller påverkar varandra." },
  { front: "utveckling", back: "När något förändras steg för steg över tid." },
  { front: "aktör", back: "En person, grupp eller stat som gör något och påverkar det som händer." },
  { front: "struktur", back: "Sådant i samhället som finns runt människor och påverkar dem, till exempel lagar, skola eller pengar." },
  { front: "följd", back: "Något som händer efteråt på grund av något annat." },
  { front: "kortsiktig", back: "Något som gäller under kort tid eller märks snabbt." },
  { front: "långsiktig", back: "Något som håller på länge eller märks först efter lång tid." },
  { front: "indirekt", back: "Något som påverkar på ett sätt som inte är rakt eller tydligt direkt." },
  { front: "perspektiv", back: "Ett sätt att se på något. Olika personer kan ha olika perspektiv på samma händelse." },
  { front: "tolkning", back: "Hur någon förstår eller förklarar något." },
  { front: "identitet", back: "Hur en person ser på sig själv och vilken grupp den känner att den hör till." },
  { front: "källa", back: "Något som berättar om det som har hänt, till exempel en text, bild eller ett föremål." },
  { front: "primärkälla", back: "En källa från den tid då något hände, eller från någon som var med." },
  { front: "sekundärkälla", back: "En källa som berättar om något i efterhand och bygger på andra källor, till exempel en historiebok." },
  { front: "källkritik", back: "Att undersöka om en källa går att lita på." },
  { front: "trovärdighet", back: "Hur mycket man kan lita på en källa eller information." },
  { front: "levnadsvillkor", back: "Hur människor lever, till exempel hur de bor, vad de äter och hur de mår." },
  { front: "arbetsvillkor", back: "Hur människor har det på jobbet, till exempel arbetstid, lön och säkerhet." },
  { front: "makt", back: "Att kunna bestämma eller påverka andra." },
  { front: "klassamhälle", back: "Ett samhälle där människor delas in i olika grupper beroende på pengar, jobb eller status." },
  { front: "kultur", back: "Hur människor lever, tänker och gör saker, till exempel språk, mat, musik och traditioner." },
  { front: "ideologi", back: "Idéer om hur ett samhälle ska fungera och styras." },
  { front: "rättighet", back: "Något som en person har rätt till, till exempel att gå i skolan eller säga sin mening." },
  { front: "skyldighet", back: "Något som en person måste eller förväntas göra." },
  { front: "demokrati", back: "Ett sätt att styra ett land där folket får vara med och bestämma, ofta genom att rösta." },
  { front: "diktatur", back: "Ett sätt att styra ett land där en person eller liten grupp bestämmer mycket och folket har lite makt." },
  { front: "monarki", back: "Ett land där kungen eller drottningen är statschef." },
  { front: "republik", back: "Ett land som inte har kung eller drottning som statschef, utan till exempel en president." },
  { front: "konflikt", back: "När personer, grupper eller länder inte är överens och det blir bråk eller kamp." },
  { front: "uppror", back: "När människor gör motstånd mot dem som bestämmer." },
  { front: "förtryck", back: "När människor behandlas orättvist och hålls nere av dem som har makt." },
  { front: "folkmord", back: "När många människor i en grupp dödas för att de tillhör just den gruppen." },
  { front: "propaganda", back: "Information som försöker få människor att tycka eller tänka på ett visst sätt." },
  { front: "censur", back: "När någon bestämmer att viss information, text eller bilder inte får visas eller spridas." },
  { front: "jämställdhet", back: "Att tjejer och killar, kvinnor och män, ska ha samma rättigheter och möjligheter." },
  { front: "jämlikhet", back: "Att alla människor är lika mycket värda och ska behandlas rättvist." },
  { front: "migration", back: "När människor flyttar från en plats till en annan." },
  { front: "emigration", back: "När människor flyttar <b>från</b> ett land." },
  { front: "immigration", back: "När människor flyttar <b>till</b> ett land." },
  { front: "välstånd", back: "När människor i ett land eller samhälle har det ganska bra med pengar, mat, bostad och andra saker de behöver." },
  { front: "globalisering", back: "När länder i världen har mer kontakt med varandra genom handel, resor, internet och kultur." },
  { front: "minoritet", back: "En mindre grupp människor i ett samhälle." },
  { front: "majoritet", back: "Den största gruppen människor i ett samhälle eller i en omröstning." },
  { front: "assimilation", back: "När människor i en mindre grupp förväntas bli mer lika majoriteten, till exempel i språk eller kultur." },
  { front: "diskriminering", back: "När någon behandlas sämre än andra på grund av till exempel kön, religion eller ursprung." },
  { front: "frihet", back: "Att kunna tänka, säga och göra saker utan att bli stoppad i onödan." },
  { front: "reform", back: "En förändring som görs för att förbättra något i samhället." },
  { front: "självständighet", back: "Att klara sig själv och bestämma över sig själv." },
  { front: "allians", back: "Ett samarbete mellan grupper eller länder." },
  { front: "neutralitet", back: "Att inte ta sida i en konflikt eller ett krig." }
];