const wordlisttitle = "Öva på begrepp om Andra världskriget";

const words = [
  
   { front: "Vilka var De Allierade?", back: "Länder som krigade tillsammans mot <b>Axelmakterna</b>.<br><br><b>De största:</b> 🇬🇧 <b>Storbritannien</b> (från 1939), 🇫🇷 <b>Frankrike</b> (1939–1940; återupptog kampen från kolonier och motståndsrörelser efter ockupationen), 🇷🇺 <b>Sovjetunionen</b> (från 1941, efter Tysklands anfall), 🇺🇸 <b>USA</b> (från 1941, efter Japans attack mot Pearl Harbor), 🇨🇳 <b>Kina</b> (krig mot Japan redan sedan 1937)." },
  { front: "Vilka var Axelmakterna?", back: "Länder som krigade tillsammans mot <b>De Allierade</b>.<br><br><b>Huvudländer:</b> 🇩🇪 <b>Tyskland</b> (under Adolf Hitler), 🇮🇹 <b>Italien</b> (under Benito Mussolini; bytte sida 1943 efter Mussolinis fall), 🇯🇵 <b>Japan</b> (under kejsar Hirohito och militärledningen). <i>Andra stater lydde eller samarbetade med dem också</i>, t.ex. Ungern, Rumänien och Bulgarien." },
  { front: "Molotov–Ribbentrop-pakten", back: "En icke-angreppspakt mellan Tyskland och Sovjetunionen, undertecknad 1939. Länderna lovade att inte anfalla varandra och delade hemligt upp Östeuropa mellan sig. Pakten gjorde det möjligt för Tyskland att starta kriget utan att frukta Sovjet." },
  { front: "Blixtkrig", back: "En ny tysk krigstaktik där man anföll snabbt och överraskande med flyg, stridsvagnar och marktrupper. Syftet var att slå ut fienden innan den hann försvara sig. Polen och Frankrike besegrades på detta sätt." },
  { front: "Annektera", back: "Att tvinga till sig ett område och göra det till en del av sitt eget land. Tyskland annekterade till exempel Österrike 1938. Ordet används ofta när ett land tar över ett annat utan att fråga." },
  { front: "Finska vinterkriget", back: "Ett krig mellan Finland och Sovjetunionen 1939–1940. Sovjet anföll för att ta delar av finskt territorium, men Finland gjorde hårt motstånd. Trots förluster lyckades Finland behålla sin självständighet." },
  { front: "Operation Weserübung", back: "Den tyska invasionen av Danmark och Norge våren 1940. Syftet var att kontrollera Atlantkusten samt säkra tillgången till järnmalm från Sverige via Norge. Danmark gav upp direkt, medan Norge kämpade i två månader." },
  { front: "Lydregim", back: "En regering som styr i ett land men egentligen kontrolleras av ett annat. Frankrike fick under kriget en lydregim i Vichy som samarbetade med Tyskland. Begreppet används när ett land förlorar sitt självbestämmande." },
  { front: "Blitzen", back: "Namnet på Tysklands bombningar av Storbritannien 1940–1941. London bombades nästan varje natt i flera månader. Trots stora skador och många döda vägrade britterna ge upp." },
  { front: "Operation Barbarossa", back: "Tysklands invasion av Sovjetunionen sommaren 1941. Det blev det största militära anfallet i historien. Operationen misslyckades till slut, vilket blev en vändpunkt i kriget." },
  { front: "Leningrad", back: "En stad i Sovjetunionen (nu S:t Petersburg) som belägrades av tyskarna i nästan 900 dagar. Hundratusentals människor svalt eller frös ihjäl. Trots det vägrade staden kapitulera." },
  { front: "Belägra", back: "Att omringa en stad eller fästning för att tvinga den att ge upp genom hunger eller isolering. Under kriget belägrades Leningrad av tyskarna. <br><br>“Armén belägrade staden i nästan tre år innan fienden drog sig tillbaka.”" },
  { front: "D-dagen", back: "De allierades invasion av Normandie den 6 juni 1944. Målet var att befria det tyskockuperade Europa. Invasionen blev en avgörande vändpunkt i kriget." },
  { front: "Förintelsen", back: "Nazitysklands systematiska utrotning av judar och andra grupper under andra världskriget. Cirka sex miljoner judar mördades i koncentrations- och förintelseläger. Förintelsen är ett av de största brotten i mänsklighetens historia." },
  { front: "Koncentrationsläger", back: "Läger där människor fängslades, tvingades arbeta och ofta dödades. Judar, romer, politiska motståndare och andra fängslades där. <br><br><b>Auschwitz</b> är det mest kända exemplet." },
  { front: "Nürnbergprocessen", back: "Rättegångarna mot nazistiska ledare efter kriget. De hölls i staden Nürnberg 1945–1946. Många dömdes till döden för krigsbrott och brott mot mänskligheten." },
  { front: "Pearl Harbor", back: "En amerikansk flottbas på Hawaii som attackerades av Japan den 7 december 1941. Anfallet förstörde stora delar av USA:s Stillahavsflotta. Efter attacken gick USA in i kriget." },
  { front: "Kapitulera", back: "Att ge upp i ett krig eller en strid. Tyskland kapitulerade den 8 maj 1945, vilket markerade slutet på kriget i Europa. <br><br>Exempel: “Efter månader av strider tvingades armén kapitulera.”" },
  { front: "Hiroshima / Nagasaki", back: "Två japanska städer som USA fällde atombomber över i augusti 1945. Hundratusentals människor dog direkt eller av strålskador. Efter bomberna tvingades Japan kapitulera och andra världskriget tog slut." }
  
];
